package edu.ankara.audiometer.ui.controller;
import edu.ankara.audiometer.application.*;import edu.ankara.audiometer.domain.model.*;import edu.ankara.audiometer.ui.view.*;import javafx.geometry.*;import javafx.scene.Parent;import javafx.scene.control.*;import javafx.scene.layout.*;import java.nio.file.Path;import java.time.LocalDateTime;
public final class MainController { private final AudiometryUseCase useCase; private final AudiogramChartPane chart=new AudiogramChartPane(); private final LogPanel log=new LogPanel(); private final ResultPanel results=new ResultPanel(); private final Label mode=new Label("Simulation Mode"); private final Label stateLabel=new Label(); public MainController(AudiometryUseCase u){useCase=u; useCase.sessions().onState(this::refresh);} public Parent root(){ BorderPane root=new BorderPane(); root.getStyleClass().add("app"); root.setTop(header()); var controls=new ControlPanel(this::start,this::present,this::manualResponse,this::autoSimulate,this::reset,this::criterionChanged); var serial=new SerialPanel(useCase.sessions().gateway(), log::add); VBox left=new VBox(12,serial,controls,currentState()); left.setPadding(new Insets(12)); left.setPrefWidth(360); SplitPane center=new SplitPane(chart, new VBox(10,results,log)); center.setDividerPositions(.62); root.setLeft(left); root.setCenter(center); refresh(useCase.sessions().state()); return root; }
 private Parent header(){ Label title=new Label("Odyometre Sistemi Tasarımı ve Testi"); title.getStyleClass().add("title"); Label sub=new Label("Functional Programming Based Audiometry Test Software"); sub.getStyleClass().add("subtitle"); mode.getStyleClass().add("mode"); VBox box=new VBox(3,title,sub,mode); box.setPadding(new Insets(14)); return box; }
 private Parent currentState(){ stateLabel.getStyleClass().add("state"); TitledPane pane=new TitledPane("Current Test State", new VBox(stateLabel)); pane.setCollapsible(false); return pane; }
 private void start(){ log.add("Test started at "+LocalDateTime.now()); useCase.sessions().presentTone(); }
 private void present(){ useCase.sessions().presentTone(); log.add("Presented tone command generated"); }
 private void manualResponse(){ useCase.sessions().response(); log.add("Incoming: RESPONSE (manual simulation)"); }
 private void autoSimulate(){ useCase.sessions().presentTone(); var s=useCase.sessions().state(); if (s.currentIntensity().value() >= useCase.simulation().thresholdFor(s.currentEar(), s.currentFrequency()).value()) useCase.sessions().response(); else useCase.sessions().noResponse(); log.add("Auto simulation step applied using configured true threshold"); }
 private void reset(){ useCase.sessions().reset(); log.add("Session reset"); }
 private void criterionChanged(ThresholdCriterion c){ useCase.sessions().setCriterion(c); log.add("Criterion changed to "+c); }
 private void refresh(TestState s){ stateLabel.setText("Ear: %s\nFrequency: %d Hz\nIntensity: %d dB HL\nPhase: %s\nResponses: %d\nThresholds: %d\nNext action: %s".formatted(s.currentEar(),s.currentFrequency().value(),s.currentIntensity().value(),s.phase(),s.eventHistory().size(),s.audiogram().points().size(),s.phase()==TestPhase.COMPLETED?"Export results":"Present tone / wait for RESPONSE")); chart.update(s.audiogram()); results.update(s.audiogram()); }
}
